### ISSUE TITLE
hGetContents: illegal operation

### ISSUE THREAD

**Issue by brent80** [maralorn/nix-output-monitor#27] opened 2021-11-01 20:16 UTC
This is on Ubuntu with nix package installer
Installed with nix-env -f default.nix -i
When I use nom I get this error
nom: <stdin>: hGetContents: illegal operation (handle is semi-closed)

Not sure why, another person with nixOS runs the same command in the same repo and it works for them.

**Comment by maralorn** [comment] 2021-11-01 20:57
I have been getting this report once in a while since this program exists. I have tried some mitigations, which fix some cases, but some others apparently not …

**Comment by maralorn** [comment] 2021-11-01 20:57
Duplicate of #23

**Closed by maralorn** 2021-11-01 20:57 UTC
